### PR TITLE
Nautilus Shell and Heart of the Sea

### PR DESCRIPTION
**Pull request by pokeblokdude**
I know @windowslogic just added these with his batch of items, but imo these fit the pack better in that they aren't just copies of the default textures.

### Me
nautilus_shell heart_of_the_sea

It's up to you to decide, of course.

### CODE REVIEW

**Comment by windowslogic** [comment]
The textures which I committed are from a version of GeruDoku which was made for 1.13/1.14. I think the Heart of the Sea fits more here because it has that medival look to it, the shell is also more detailed in my opinion and fits the medival style of GeruDoku more.

**Comment by sybenx** [comment]
i agree with pokeblokdude in this case. Many textures in GeruDoku are significantly different in color or form from default Minecraft. Although Barytyrannus did add those textures before I started working on the pack, his edits aren't necessarily true to the pack used by the Yogscast. Anyone is free to fork the pack if they want to go a different route, e.g. [Gerudoku Genesis (Tydoku)](https://www.curseforge.com/minecraft/texture-packs/gerudoku-genesis).

**Comment by pokeblokdude** [comment]
@Syberiyxx idk if it's what you meant to do, but my textures don't appear to have been added

**Comment by sybenx** [comment]
they've been added, the textures will be pushed out with the next version update

**Comment by pokeblokdude** [comment]
Ah ok I cloned the repo and turns out github is just being weird when displaying image previews

**Pull request merged**
